# Generated by Django 4.2 on 2024-11-05 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TipoEntrada', '0001_initial'),
        ('CostaRica', '0001_initial'),
        ('Hondura', '0001_initial'),
        ('Nicaragua', '0001_initial'),
        ('Panama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaentrada', models.CharField(max_length=100, verbose_name='FechaEntrada')),
                ('sucursalid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Nicaragua.sucursal', verbose_name='Sucursal')),
                ('sucursalidcos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CostaRica.sucursalcos', verbose_name='Sucursalcos')),
                ('sucursalidhon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Hondura.sucursalhon', verbose_name='SucursalHon')),
                ('sucursalidpan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Panama.sucursalpan', verbose_name='SucursalPan')),
                ('tipoentrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TipoEntrada.tipoentrada', verbose_name='TipoEntrada')),
            ],
            options={
                'verbose_name': 'Entradas',
            },
        ),
    ]
