# Generated by Django 4.2 on 2024-11-08 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CostaRica', '0002_alter_sucursalcos_options'),
        ('Entrada', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='sucursalidcos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='CostaRica.sucursalcos', verbose_name='SucursalCos'),
        ),
    ]
