# Generated by Django 4.2 on 2024-11-05 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DetalleEntrada', '0001_initial'),
        ('LibrosPan', '0001_initial'),
        ('Libros', '0001_initial'),
        ('LibrosHon', '0001_initial'),
        ('LibrosCos', '0001_initial'),
        ('Entrada', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleentrada',
            name='entrada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Entrada.entrada', verbose_name='Entrada'),
        ),
        migrations.AddField(
            model_name='detalleentrada',
            name='libro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Libros.libro', verbose_name='Libro'),
        ),
        migrations.AddField(
            model_name='detalleentrada',
            name='librocos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LibrosCos.libroscos', verbose_name='LibroCos'),
        ),
        migrations.AddField(
            model_name='detalleentrada',
            name='librohon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LibrosHon.libroshon', verbose_name='LibroHon'),
        ),
        migrations.AddField(
            model_name='detalleentrada',
            name='libropan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='LibrosPan.librospan', verbose_name='LibroPan'),
        ),
    ]
