# Generated by Django 4.2 on 2024-11-12 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibrosCos', '0001_initial'),
        ('LibrosHon', '0001_initial'),
        ('LibrosPan', '0001_initial'),
        ('Libros', '0001_initial'),
        ('DetalleSalida', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesalida',
            name='libro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Libros.libro', verbose_name='Libro'),
        ),
        migrations.AlterField(
            model_name='detallesalida',
            name='librocos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='LibrosCos.libroscos', verbose_name='LibroCos'),
        ),
        migrations.AlterField(
            model_name='detallesalida',
            name='librohon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='LibrosHon.libroshon', verbose_name='LibroHon'),
        ),
        migrations.AlterField(
            model_name='detallesalida',
            name='libropan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='LibrosPan.librospan', verbose_name='LibroPan'),
        ),
    ]
