# Generated by Django 4.2 on 2024-11-05 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hondura', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursalhon',
            options={'verbose_name': 'SucursalHon'},
        ),
    ]
