# Generated by Django 4.2 on 2024-11-14 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TipoSalida', '0001_initial'),
        ('Panama', '0001_initial'),
        ('Nicaragua', '0001_initial'),
        ('Hondura', '0001_initial'),
        ('CostaRica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechasalida', models.CharField(max_length=100, verbose_name='FechaSalida')),
                ('sucursalid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Nicaragua.sucursal', verbose_name='Sucursal')),
                ('sucursalidcos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CostaRica.sucursalcos', verbose_name='Sucursalcos')),
                ('sucursalidhon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Hondura.sucursalhon', verbose_name='SucursalHon')),
                ('sucursalidpan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Panama.sucursalpan', verbose_name='SucursalPan')),
                ('tiposalida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='TipoSalida.tiposalida', verbose_name='TipoSalida')),
            ],
        ),
    ]
