# Generated by Django 4.2 on 2024-11-12 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Panama', '0001_initial'),
        ('Hondura', '0002_alter_sucursalhon_options'),
        ('CostaRica', '0002_alter_sucursalcos_options'),
        ('Salida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='sucursalidcos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='CostaRica.sucursalcos', verbose_name='Sucursalcos'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='sucursalidhon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Hondura.sucursalhon', verbose_name='SucursalHon'),
        ),
        migrations.AlterField(
            model_name='salida',
            name='sucursalidpan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Panama.sucursalpan', verbose_name='SucursalPan'),
        ),
    ]
