# Generated by Django 4.2 on 2024-11-14 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibrosHon', '0001_initial'),
        ('LibrosCos', '0001_initial'),
        ('Libros', '0001_initial'),
        ('LibrosPan', '0001_initial'),
        ('TipoSalida', '0001_initial'),
        ('Salida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalidaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'SalidasDetalles',
            },
        ),
        migrations.AlterModelOptions(
            name='salida',
            options={'verbose_name': 'Salidas'},
        ),
        migrations.AlterField(
            model_name='salida',
            name='tiposalida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='TipoSalida.tiposalida', verbose_name='TipoSalida'),
        ),
        migrations.CreateModel(
            name='DetalleSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costosalida', models.BigIntegerField(blank=True, null=True, verbose_name='CostoSalida')),
                ('cantidad', models.BigIntegerField(blank=True, null=True, verbose_name='Cantidad')),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Libros.libro', verbose_name='Libro')),
                ('librocos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='LibrosCos.libroscos', verbose_name='LibroCos')),
                ('librohon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='LibrosHon.libroshon', verbose_name='LibroHon')),
                ('libropan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='LibrosPan.librospan', verbose_name='LibroPan')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Salida.salida', verbose_name='Salida')),
            ],
        ),
    ]
